module WowArmory
  class Cascdataxb
    unloadable
  
    include Constants

    @item_data = nil

    def item_data
      @@item_data ||= Hash.new.tap do |hash|
        # loop through each line of the casc data generated by the script and
        # parse it as json. for each row, stick an entry in the hash mapping
        # the item ID to the item data
        jsondata = JSON.parse(File.read(File.dirname(__FILE__), "cascdata", "Items.json"))
        jsondata['items'].each do |item|
          hash[item['id']] = item
        end
      end
    end
  end
end
